function [RetVaR SSVaR SCVaR Simr]=MCSimVaR(S,p,T)
r=price2ret(S);
Mu=mean(r);
Sigma=std(r);
S0=S(end,1);
SimS=GBMSim(T+1,10000,1,Mu,Sigma,S0);
SimST=SimS(end,:)';
Simr=log(SimST/S0);
RetVaR=quantile(Simr,p);
SSVaR=-S0*(RetVaR);
SCVaR=-S0*(exp(RetVaR)-1);